# global:
#   scrape_interval: 5s

# scrape_configs:
  
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['127.0.0.1:9090'] 

#   - job_name: 'docker'
#     static_configs:
#       - targets: ['host.docker.internal:9323'] 


scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - <Your_Private_ip_address>:9090
     
  
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - <Your_Private_ip_address>:8080


  - job_name: docker
    scrape_interval: 5s
    static_configs:
    - targets: ['<Your_Private_ip_address>:9323']
    

