name: Deploy on Server with SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy compose.yml 
        
        env:
          TARGET_PATH: ${{ env.TARGET_PATH }}
        run: |
          cp -f compose.yml $TARGET_PATH
          echo "compose.yml successfully copied to $TARGET_PATH"
          docker-compose down
          docker-compose up -d

        
      
