name: Deploy on Server with SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy compose.yml 
        
        env:
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          cp compose.yml /home/student/

        
      
