name: Deploy on Server 

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy compose.yml & restart Docker services
        
        env:
          TARGET_PATH: ${{ vars.TARGET_PATH }}
        run: |
          echo "copie to $TARGET_PATH"
          cp  compose.yml "$TARGET_PATH"
          echo "compose.yml successfully copied to $TARGET_PATH"
          cd "$TARGET_PATH"
          docker compose down
          docker compose up -d
          docker ps

        
      
