name: Deploy on Server with SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy compose.yml & prometheus.yml via SCP
        env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no docker-compose.yml  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:

        
      - name: Run multiple command to deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.TARGET_PATH }}
            docker-compose down
            docker-compose up -d 
            docker ps

